import { contextBridge, ipcRenderer } from "electron";
import type { FreeCordBridge } from "../shared/bridge";

const bridge: FreeCordBridge = {
  getRuntimeInfo: () => ipcRenderer.invoke("runtime:get-info"),
  openSupportPage: () => ipcRenderer.invoke("runtime:open-support-page"),
  getWindowFullscreen: () => ipcRenderer.invoke("window:get-fullscreen"),
  setWindowFullscreen: (fullscreen) => ipcRenderer.invoke("window:set-fullscreen", fullscreen),
  onWindowFullscreenChanged: (listener) => {
    const wrapped = (_event: Electron.IpcRendererEvent, fullscreen: unknown) => listener(fullscreen === true);
    ipcRenderer.on("window:fullscreen-changed", wrapped);
    return () => ipcRenderer.removeListener("window:fullscreen-changed", wrapped);
  },
  prepareLinuxScreenAudio: () => ipcRenderer.invoke("audio:prepare-linux-screen"),
  unmuteLinuxScreenAudio: () => ipcRenderer.invoke("audio:unmute-linux-screen"),
  releaseLinuxScreenAudio: () => ipcRenderer.invoke("audio:release-linux-screen"),
  getServerSettings: () => ipcRenderer.invoke("settings:get-server"),
  saveServerSettings: (input) => ipcRenderer.invoke("settings:save-server", input),
  clearServerSettings: () => ipcRenderer.invoke("settings:clear-server"),
  getAudioSettings: () => ipcRenderer.invoke("settings:get-audio"),
  saveAudioSettings: (settings) => ipcRenderer.invoke("settings:save-audio", settings),
  login: (input) => ipcRenderer.invoke("auth:login", input),
  register: (input) => ipcRenderer.invoke("auth:register", input),
  refresh: () => ipcRenderer.invoke("auth:refresh"),
  logout: () => ipcRenderer.invoke("auth:logout"),
  updateStatus: (status) => ipcRenderer.invoke("auth:update-status", status),
  updateProfile: (input) => ipcRenderer.invoke("profile:update", input),
  changePassword: (input) => ipcRenderer.invoke("profile:change-password", input),
  getSessionState: () => ipcRenderer.invoke("auth:get-session-state"),
  clearCredentials: () => ipcRenderer.invoke("auth:clear-credentials"),
  getChannels: () => ipcRenderer.invoke("community:get-channels"),
  createChannel: (input) => ipcRenderer.invoke("community:create-channel", input),
  updateChannel: (channelId, name) => ipcRenderer.invoke("community:update-channel", { channelId, name }),
  deleteChannel: (channelId) => ipcRenderer.invoke("community:delete-channel", channelId),
  searchGiphy: (query) => ipcRenderer.invoke("media:search-giphy", query),
  getMembers: () => ipcRenderer.invoke("community:get-members"),
  createInvite: (expiresInSeconds) => ipcRenderer.invoke("community:create-invite", expiresInSeconds),
  getCommunityPermissions: () => ipcRenderer.invoke("community:get-permissions"),
  getCommunityRoles: () => ipcRenderer.invoke("community:get-roles"),
  createCommunityRole: (input) => ipcRenderer.invoke("community:create-role", input),
  updateCommunityRole: (roleId, input) => ipcRenderer.invoke("community:update-role", { roleId, input }),
  deleteCommunityRole: (roleId) => ipcRenderer.invoke("community:delete-role", roleId),
  assignMemberRole: (userId, roleId) => ipcRenderer.invoke("community:assign-member-role", { userId, roleId }),
  removeMemberRole: (userId, roleId) => ipcRenderer.invoke("community:remove-member-role", { userId, roleId }),
  resetMemberPassword: (userId, newPassword) => ipcRenderer.invoke("community:reset-member-password", { userId, newPassword }),
  deactivateMember: (userId) => ipcRenderer.invoke("community:deactivate-member", userId),
  clearMemberVoiceRestrictions: (userId) => ipcRenderer.invoke("community:clear-member-voice-restrictions", userId),
  removeMyAvatar: () => ipcRenderer.invoke("profile:remove-avatar"),
  uploadAvatar: (input) => ipcRenderer.invoke("profile:upload-avatar", input),
  getCommunityEmotes: () => ipcRenderer.invoke("community:get-emotes"),
  deleteCommunityEmote: (emoteId) => ipcRenderer.invoke("community:delete-emote", emoteId),
  uploadCommunityEmote: (input) => ipcRenderer.invoke("community:upload-emote", input),
  chooseAndUploadMedia: () => ipcRenderer.invoke("media:choose-and-upload"),
  getMediaImageData: (assetId) => ipcRenderer.invoke("media:get-image-data", assetId),
  addEmoteReaction: (channelId, messageId, emoteId) => ipcRenderer.invoke("chat:add-emote-reaction", { channelId, messageId, emoteId }),
  removeEmoteReaction: (channelId, messageId, emoteId) => ipcRenderer.invoke("chat:remove-emote-reaction", { channelId, messageId, emoteId }),
  getMessages: (channelId, before) => ipcRenderer.invoke("chat:get-messages", { channelId, before }),
  getMessage: (channelId, messageId) => ipcRenderer.invoke("chat:get-message", { channelId, messageId }),
  getSharedFiles: (before) => ipcRenderer.invoke("community:get-shared-files", before),
  getAuditLog: (before) => ipcRenderer.invoke("community:get-audit-log", before),
  onRealtimeEvent: (listener) => {
    const wrapped = (_event: Electron.IpcRendererEvent, payload: unknown) => listener(payload as Parameters<typeof listener>[0]);
    ipcRenderer.on("realtime:event", wrapped);
    return () => ipcRenderer.removeListener("realtime:event", wrapped);
  },
  sendMessage: (channelId, payload) => ipcRenderer.invoke("chat:send-message", { channelId, ...payload }),
  editMessage: (channelId, messageId, payload) => ipcRenderer.invoke("chat:edit-message", { channelId, messageId, ...payload }),
  deleteMessage: (channelId, messageId) => ipcRenderer.invoke("chat:delete-message", { channelId, messageId }),
  addReaction: (channelId, messageId, target) => ipcRenderer.invoke("chat:add-reaction", { channelId, messageId, target }),
  removeReaction: (channelId, messageId, target) => ipcRenderer.invoke("chat:remove-reaction", { channelId, messageId, target }),
  muteVoiceParticipant: (channelId, userId, muted) => ipcRenderer.invoke("voice:moderate-mute", { channelId, userId, muted }),
  disconnectVoiceParticipant: (channelId, userId) => ipcRenderer.invoke("voice:moderate-disconnect", { channelId, userId }),
  moveVoiceParticipant: (channelId, userId, destinationChannelId) => ipcRenderer.invoke("voice:moderate-move", { channelId, userId, destinationChannelId }),
  getFilesSurfaceInfo: () => ipcRenderer.invoke("files:get-info"),
  showFilesSurface: (rect) => ipcRenderer.invoke("files:show", rect),
  hideFilesSurface: () => ipcRenderer.invoke("files:hide"),
  showFilesView: (rect) => ipcRenderer.invoke("files:show", rect),
  updateFilesViewBounds: (rect) => ipcRenderer.invoke("files:update-bounds", rect),
  hideFilesView: () => ipcRenderer.invoke("files:hide-void"),
  getChatKey: () => ipcRenderer.invoke("chat:get-key"),
  issueVoiceToken: (channelId) => ipcRenderer.invoke("voice:issue-token", channelId),
};

contextBridge.exposeInMainWorld("freecord", bridge);
